project:
  type: website
  output-dir: docs
  resources:
    - "media/nft_monkey.glb"
    - "media/heron.glb"

execute:
  enabled: true
  python: "./renv/python/virtualenvs/renv-python-3.11/bin/python"

website:
  title: "Shaun Porwal"
  favicon: "./media/favicon.png"
  navbar:
    right:
      - text: About
        href: about.html
      - text: Blog
        href: index.html
      - text: CV
        href: ./media/porwal_resume.pdf
        target: _blank
      - text: Projects
        href: projects.html
      - text: X
        href: https://x.com/shaunporwal
        target: _blank

format:
  html:
    theme:
      dark: darkly
    css: styles.css

editor: visual
