project:
  type: website
  output-dir: docs

execute:
  enabled: true
  python: "./renv/python/virtualenvs/renv-python-3.11/bin/python"

website:
  title: "Shaun Porwal"
  navbar:
    right:
      - about.qmd
      - text: Blog
        href: index.html
      - text: CV
        href: porwal_resume.pdf
        target: _blank
      - projects.qmd
      - icon: github
        href: https://github.com/shaunporwal
      - icon: twitter
        href: https://x.com/ShaunPorwal
format:
  html:
    theme: minty
    css: styles.css

editor: visual
