project:
  type: website
  output-dir: docs

execute:
  enabled: true
  python: "./renv/python/virtualenvs/renv-python-3.11/bin/python"

website:
  title: "Shaun Porwal"
  navbar:
    right:
      - text: Blog
        href: index.html
      - text: cv
        href: https://rxresu.me/shaunporwal/241206-resume
      - text: Projects
        href: projects.html
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css


editor: visual

