project:
  type: website
  output-dir: docs
  resources:
    - "media/heron.glb"
    - "media/nft_monkey.glb"
    - "media/banana_upright2.glb"
    - "media/260608-iphone-macro-eye.png"

execute:
  enabled: true
  python: "./renv/python/virtualenvs/renv-python-3.11/bin/python"

website:
  title: "Shaun Porwal"
  favicon: "./media/favicon.png"
  google-analytics: "G-17E2H549JP"
  navbar:
    right:
      - text: "📅 Book a Call"
        href: "https://cal.com/shaun-porwal/30min?overlayCalendar=true"
        target: _blank
      - text: About
        href: about.html
      - text: Stuff
        href: stuff.html
      - text: Blog
        href: index.html
      - text: Docs
        menu:
          - text: CV
            href: ./media/porwal-resume.pdf
            target: _blank
          - text: 2015 NTU Mandarin
            href: ./media/2015_ntu_mandarin_cert_and_grade.pdf
            target: _blank
      - icon: github
        href: https://github.com/shaunporwal
        target: _blank
      - text: X
        href: https://x.com/shaunporwal
        target: _blank

format:
  html:
    theme: darkly
    css:
      - styles/palette.css
      - styles/base.css
      - styles/navbar.css
      - styles/models.css

editor: visual
