project:
  type: website
  output-dir: docs
  resources:
    - "media/heron.glb"
    - "media/banana3.glb"
    - "media/banana_remeshed1.glb"

execute:
  enabled: true
  python: "./renv/python/virtualenvs/renv-python-3.11/bin/python"

website:
  title: "Shaun Porwal"
  favicon: "./media/favicon.png"
  google-analytics: "G-17E2H549JP"
  navbar:
    right:
      - text: About
        href: about.html
      - text: Blog
        href: index.html
      - text: Docs
        menu:
          - text: CV
            href: ./media/porwal-resume.pdf
            target: _blank
          - text: 2015 NTU Mandarin
            href: ./media/2015_ntu_mandarin_cert_and_grade.pdf
            target: _blank
      - icon: github
        href: https://github.com/shaunporwal
        target: _blank
      - text: X
        href: https://x.com/shaunporwal
        target: _blank

format:
  html:
    theme:
      dark: darkly
    css: styles.css

editor: visual
