---
title: "SP: Homepage"
output:
  html_document:
    toc: true
    toc_float:
      smooth_scroll: TRUE
    toc_depth: 2
    toc_collapse: true
---

<style>
.title{
  display: none;
}
</style>

```{css, index, echo=FALSE}
.contact-box {
  position: relative;
  border: 2px solid lightgrey;
  padding: 20px;
  margin-bottom: 20px;
  border-radius: 10px;
  background-color: #f9f9f9;
}

.contact-wrapper {
  display: flex;
}

.contact-text {
  flex-grow: 1;
}

.link {
  text-decoration: none;
  color: #007bff;
}

.link:hover {
  text-decoration: underline;
}

.date {
  position: absolute;
  top: 10px;
  right: 10px;
  font-weight: bold;
  padding-left: 10px; /* Add left padding to separate the year from the text */
}

h2 {
  margin-bottom: 10px;
  font-size: 1.3em;
  margin-right: 50px; /* Add right margin to separate the title from the year */
}

p {
  margin-bottom: 0;
}

/* Custom CSS for the table of contents */
.tocify-item {
  display: block;
  text-indent: 0em;
  padding-right: 0em;
}

.tocify-item .tocify-header1 {
  display: inline-block;
  text-indent: 0;
  padding-left: 0;
}

.tocify-item .tocify-header2 {
  display: inline-block;
  text-indent: 0;
  padding-left: 0;
}

.tocify-item .tocify-header2 > span {
  display: inline-block;
  text-indent: 0;
  padding-left: 0;
}

.tocify-item.active {
  background-color: rgba(92, 184, 92, 0.2); /* Green with 50% transparency */
  color: rgba(92, 184, 92, 0.5);
}

.tocify-item:hover {
  background-color: rgba(100, 149, 237, 0.5); /* Light blue with transparency */
  color: #ffffff;
}

/* Add or modify the following CSS in your existing CSS code */

.tocify-item.active:hover {
  background-color: rgba(92, 184, 92, 0.7); /* Slightly transparent version of the active color */
  color: #ffffff;
}

```

*Welcome to my personal space! This site serves as a home for my projects, thoughts, and other content.*

# **Thoughts & Experiences**

<div class="contact-wrapper contact-box">
<div class="contact-text">
<h2>Understanding How to Trigger My Motivation</h2>
<span class="date">05/29/23</span>
<p> 
I think one of the biggest saps on my motivation is having too many distractions. If I remove as many distractions as I can and focus on my main priority for the time being, I am able to knock it out and go down the list, retaining my drive and finishing everything efficiently. If I have too much going on all at once, I tend to get distracted and get very little done, and am demotivated, partially due to my lack of progress. 

At work, unfortunately, all of my work has to be done on top of each other, and priorities seem to shuffle around some times. I also have my manager and boss reaching out all the time, adding things to my plate. I need to learn how to communicate around this effectively so that I can manage expectations and keep my sanity. 

I think one thing I'd like to try is consistently putting greater focus on the top priority, and completely ignoring everything else.
</p>
</div>
</div>

<div class="contact-wrapper contact-box">
<div class="contact-text">
<h2><a href="https://www.strava.com/activities/8857158962" class="link">230411 Strava Running Thoughts</a></h2>
<span class="date">04/08/23</span>
<p>
Even if we don't intend to, we subconsciously end up copying those around us in
our thoughts and actions. Therefore, other people can only stand in the way of
self-understanding and development.

This is also why it's easier to run or learn in groups. We can forego the 
conscious effort in favor of subconscious memetic behavior.
</p>
</div>
</div>

<div class="contact-wrapper contact-box">
<div class="contact-text">
<h2><a href="https://www.strava.com/activities/8857158962" class="link">230408 Strava Running Thoughts</a></h2>
<span class="date">04/08/23</span>
<p> 
Man, I just have to say, so many people are so lost in this world, and it's so
easy to get distracted by the noise.

If you always listen to your inner voice and just do what you want, while
maintaining compassion for others, you can safely disregard anything anybody
tells you about what they think you "should" do.

Internal critical thinking is more important to follow than any
rule/prescription/suggestion from any person, no matter how important.
</p>
</div>
</div>

```{r render all other Rmds, echo=FALSE, include=FALSE}

rmarkdown::render('projects.Rmd')
rmarkdown::render('readings.Rmd')


```













