[project]
name = "shaunporwal-github-io"
version = "0.1.0"
description = "Shaun Personal Site"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "pip>=24.3.1",
    "pyyaml>=6.0.2",
]
