name: Quarto Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-root

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: latest  # Specifying a fixed version instead of 'latest'

      - name: Render Quarto Project
        run: |
          poetry run quarto render

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: _site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}